apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  # Allow management of all cluster resources
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow deployment to any namespace
  destinations:
  - namespace: '*'
    server: '*'
  # Allow any source repository
  sourceRepos:
  - '*'
  # Allow all OCI repositories
  sourceNamespaces:
  - '*'
