namespace: {{ .kcm.namespace }}

resources: []

patches:
  - target:
      kind: Credential
      labelSelector: "k0rdent.credentials.provider=azure"
    patch: |
      - op: replace
        path: /spec/identityRef/namespace
        value: {{ .kcm.namespace }}