---
{{- if eq .gitops.tool "argo" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k0rdent-platform
  namespace: {{ .gitops.argo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/{{ .gitops.github.username }}/{{ .gitops.github.repository }}.git
    targetRevision: {{ .gitops.github.branch }}
    path: "./management-clusters/{{ $managementCluster }}/components/k0rdent"
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .gitops.argo.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k0rdent-configuration
  namespace: {{ .gitops.argo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/{{ .gitops.github.username }}/{{ .gitops.github.repository }}.git
    targetRevision: {{ .gitops.github.branch }}
    path: "./management-clusters/{{ $managementCluster }}/k0rdent"
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .gitops.argo.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ else if eq .gitops.tool "flux" }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k0rdent-configuration
  namespace: {{ .gitops.flux.namespace }}
spec:
  interval: 1m0s
  ref:
    branch: {{ .gitops.github.branch }}
  url: https://github.com/{{ .gitops.github.username }}/{{ .gitops.github.repository }}.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k0rdent-platform
  namespace: {{ .gitops.flux.namespace }}
spec:
  interval: 10m0s
  path: ./management-clusters/{{ $managementCluster }}/components/k0rdent
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: {{ .gitops.flux.namespace }}
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: managements.k0rdent.mirantis.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: accessmanagements.k0rdent.mirantis.com
    - apiVersion: apps/v1
      kind: Deployment
      name: kcm-controller-manager
      namespace: kcm-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k0rdent-configuration
  namespace: {{ .gitops.flux.namespace }}
spec:
  interval: 10m0s
  path: ./management-clusters/{{ $managementCluster }}/k0rdent
  prune: true
  sourceRef:
    kind: GitRepository
    name: k0rdent-configuration
    namespace: {{ .gitops.flux.namespace }}
  dependsOn:
    - name: k0rdent-platform
{{ else }}
  {{- fail "Unrecognized value for '.gitops.tool'. Allowed values are 'flux' and 'argo'" }}
{{ end}}
