---
apiVersion: cluster.k0rdent.io/v1alpha1
kind: ClusterDeployment
metadata:
  name: {{ (ds "cluster").cluster_name }}
  labels:
    environment: {{ (ds "cluster").environment }}
    team: {{ (ds "cluster").team }}
    purpose: {{ (ds "cluster").purpose }}
    cost-center: {{ (ds "cluster").cost_center }}
    k0rdent.io/managed: "true"
spec:
  clusterName: {{ (ds "cluster").cluster_name }}
  provider: aws
  region: {{ (ds "cluster").region }}
  version: "1.26"
  controlPlane:
    instanceType: {{ (ds "cluster").control_plane_instance_type }}
    count: 1
    spotInstances: false
  workers:
    instanceType: {{ (ds "cluster").worker_instance_type }}
    count: {{ (ds "cluster").node_count }}
    minCount: {{ (ds "cluster").min_node_count }}
    maxCount: {{ (ds "cluster").max_node_count }}
    spotInstances: false
  networking:
    podCIDR: "192.168.0.0/16"
    serviceCIDR: "10.96.0.0/12"
  addons:
    ingressController: true
    certManager: true
    monitoring: true
    logging: true
  tags:
    environment: {{ (ds "cluster").environment }}
    team: {{ (ds "cluster").team }}
    purpose: {{ (ds "cluster").purpose }}
    cost-center: {{ (ds "cluster").cost_center }}
    created-by: "k0rdent-fluxcd" 