---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ .gitops.argo.namespace }}
resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd//manifests/{{ .gitops.argo.flavor }}?ref={{ .gitops.argo.version }}
