apiVersion: k0rdent.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: azure-credential
  labels:
    k0rdent.credentials.provider: azure
spec:
  description: "Azure credentials"
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: azure-cluster-identity
    namespace: "" # change it
