apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ClusterDeployment
metadata:
  name: cluster-deployment
  labels: {}
spec:
  template: "" # change it
  credential: "" # change it
  serviceSpec:
    services: []
  config:
    controlPlaneNumber: 1
    workersNumber: 2
    controlPlane: {}
    worker: {}