name: Process Cluster Request

on:
  # Triggered when a PR with the cluster-request label is approved
  pull_request_review:
    types: [submitted]

jobs:
  process-cluster-request:
    # This workflow prepares the cluster configuration files
    # The actual cluster deployment happens after the PR is merged
    # See deploy-cluster-on-merge.yml for the deployment workflow
    if: |
      github.event.review.state == 'approved' &&
      contains(github.event.pull_request.labels.*.name, 'cluster-request')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CLUSTER_REQUEST_PAT }}
          
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
        
      - name: Fetch PR details
        id: pr_details
        run: |
          # Store PR number for later use
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          
          # Fetch PR details using GitHub CLI and save to file
          gh pr view ${{ github.event.pull_request.number }} --json body -q .body > pr_body.txt
          
          echo "PR body saved to pr_body.txt"
        env:
          GH_TOKEN: ${{ secrets.CLUSTER_REQUEST_PAT }}
          
      - name: Extract cluster information from PR
        id: extract_cluster_info
        run: |
          # Extract required parameters from PR body
          CLUSTER_NAME=$(grep -A 1 "**Cluster Name**:" pr_body.txt | tail -n 1 | tr -d ' ')
          ENVIRONMENT=$(grep -A 1 "**Environment**:" pr_body.txt | tail -n 1 | tr -d ' ')
          PROVIDER=$(grep -A 10 "**Provider**:" pr_body.txt | grep -m 1 "^- " | tr -d '- ' | tr -d ' ')
          MANAGEMENT_CLUSTER=$(grep -A 1 "**Management Cluster**:" pr_body.txt | tail -n 1 | tr -d ' ')
          REGION=$(grep -A 1 "**Region/Location**:" pr_body.txt | tail -n 1 | tr -d ' ')
          
          # Resource size - need to parse from multiline
          RESOURCE_SIZE=$(grep -A 5 "**Resource Size**:" pr_body.txt | tail -n 5 | grep -v "<!--")
          if [[ "$PROVIDER" == *"aws"* ]]; then
            CONTROL_PLANE_INSTANCE_TYPE=$(echo "$RESOURCE_SIZE" | grep -i "control plane" | grep -o "t[0-9]\.[a-z0-9]*\|m[0-9]\.[a-z0-9]*\|c[0-9]\.[a-z0-9]*" || echo "t3.medium")
            WORKER_INSTANCE_TYPE=$(echo "$RESOURCE_SIZE" | grep -i "worker" | grep -o "t[0-9]\.[a-z0-9]*\|m[0-9]\.[a-z0-9]*\|c[0-9]\.[a-z0-9]*" || echo "t3.large")
          elif [[ "$PROVIDER" == *"azure"* ]]; then
            CONTROL_PLANE_INSTANCE_TYPE=$(echo "$RESOURCE_SIZE" | grep -i "control plane" | grep -o "Standard_[A-Za-z][0-9]\S*" || echo "Standard_D2s_v3")
            WORKER_INSTANCE_TYPE=$(echo "$RESOURCE_SIZE" | grep -i "worker" | grep -o "Standard_[A-Za-z][0-9]\S*" || echo "Standard_D4s_v3")
          else
            CONTROL_PLANE_INSTANCE_TYPE="medium"
            WORKER_INSTANCE_TYPE="large"
          fi
          
          NODE_COUNT=$(grep -A 1 "**Node Count**:" pr_body.txt | tail -n 1 | tr -d ' ' || echo "2")
          MIN_NODE_COUNT=$(echo "$NODE_COUNT" | awk '{print ($1 > 1) ? $1 - 1 : $1}')
          MAX_NODE_COUNT=$(echo "$NODE_COUNT" | awk '{print $1 * 2}')
          
          TEAM=$(grep -A 1 "**Team**:" pr_body.txt | tail -n 1 | tr -d ' ')
          PURPOSE=$(grep -A 1 "**Purpose**:" pr_body.txt | tail -n 1 | tr -d ' ')
          COST_CENTER=$(grep -A 1 "**Cost Center**:" pr_body.txt | tail -n 1 | tr -d ' ' || echo "default")
          
          # Validate required parameters
          if [ -z "$CLUSTER_NAME" ] || [ -z "$PROVIDER" ] || [ -z "$MANAGEMENT_CLUSTER" ]; then
            echo "Error: Missing required parameters in PR description"
            exit 1
          fi
          
          # Debug output
          echo "Extracted parameters:"
          echo "CLUSTER_NAME: $CLUSTER_NAME"
          echo "ENVIRONMENT: $ENVIRONMENT"
          echo "PROVIDER: $PROVIDER"
          echo "MANAGEMENT_CLUSTER: $MANAGEMENT_CLUSTER"
          echo "REGION: $REGION"
          echo "CONTROL_PLANE_INSTANCE_TYPE: $CONTROL_PLANE_INSTANCE_TYPE"
          echo "WORKER_INSTANCE_TYPE: $WORKER_INSTANCE_TYPE"
          echo "NODE_COUNT: $NODE_COUNT"
          
          # Set outputs
          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "PROVIDER=$PROVIDER" >> $GITHUB_ENV
          echo "MANAGEMENT_CLUSTER=$MANAGEMENT_CLUSTER" >> $GITHUB_ENV
          echo "REGION=$REGION" >> $GITHUB_ENV
          echo "CONTROL_PLANE_INSTANCE_TYPE=$CONTROL_PLANE_INSTANCE_TYPE" >> $GITHUB_ENV
          echo "WORKER_INSTANCE_TYPE=$WORKER_INSTANCE_TYPE" >> $GITHUB_ENV
          echo "NODE_COUNT=$NODE_COUNT" >> $GITHUB_ENV
          echo "MIN_NODE_COUNT=$MIN_NODE_COUNT" >> $GITHUB_ENV
          echo "MAX_NODE_COUNT=$MAX_NODE_COUNT" >> $GITHUB_ENV
          echo "TEAM=$TEAM" >> $GITHUB_ENV
          echo "PURPOSE=$PURPOSE" >> $GITHUB_ENV
          echo "COST_CENTER=$COST_CENTER" >> $GITHUB_ENV
      
      - name: Generate Cluster Deployment file
        run: |
          TARGET_DIR="management-clusters/${{ env.MANAGEMENT_CLUSTER }}/k0rdent/cluster-deployments/${{ env.CLUSTER_NAME }}"
          mkdir -p "$TARGET_DIR"
          
          # Copy and fill the template
          TEMPLATE_FILE=".github/templates/cluster-deployments/${{ env.PROVIDER }}/template.yaml"
          if [ ! -f "$TEMPLATE_FILE" ]; then
            echo "Error: Template for provider ${{ env.PROVIDER }} not found"
            exit 1
          fi
          
          # Use envsubst to replace variables in the template
          cat "$TEMPLATE_FILE" | \
          envsubst '$CLUSTER_NAME $ENVIRONMENT $REGION $CONTROL_PLANE_INSTANCE_TYPE $WORKER_INSTANCE_TYPE $NODE_COUNT $MIN_NODE_COUNT $MAX_NODE_COUNT $TEAM $PURPOSE $COST_CENTER' \
          > "$TARGET_DIR/cluster-deployment.yaml"
          
          # Create kustomization.yaml
          cat > "$TARGET_DIR/kustomization.yaml" << EOF
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
          - cluster-deployment.yaml
          EOF
          
          # Update main kustomization.yaml for cluster-deployments
          MAIN_KUSTOMIZATION="management-clusters/${{ env.MANAGEMENT_CLUSTER }}/k0rdent/cluster-deployments/kustomization.yaml"
          
          # Create the main kustomization.yaml if it doesn't exist
          if [ ! -f "$MAIN_KUSTOMIZATION" ]; then
            mkdir -p $(dirname "$MAIN_KUSTOMIZATION")
            cat > "$MAIN_KUSTOMIZATION" << EOF
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources: []
          EOF
          fi
          
          if grep -q "${{ env.CLUSTER_NAME }}" "$MAIN_KUSTOMIZATION"; then
            echo "Cluster already exists in kustomization.yaml, skipping update"
          else
            # Check if resources: [] is in the file and replace it
            if grep -q "resources: \[\]" "$MAIN_KUSTOMIZATION"; then
              sed -i "s|resources: \[\]|resources:\n- ${{ env.CLUSTER_NAME }}|g" "$MAIN_KUSTOMIZATION"
            else
              # Append to existing resources list
              sed -i "/resources:/a \ - ${{ env.CLUSTER_NAME }}" "$MAIN_KUSTOMIZATION"
            fi
          fi
          
          # Add a file containing deployment metadata for tracking
          cat > "$TARGET_DIR/k0rdent-metadata.yaml" << EOF
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: ${{ env.CLUSTER_NAME }}-metadata
            namespace: k0rdent-system
          data:
            cluster_name: "${{ env.CLUSTER_NAME }}"
            provider: "${{ env.PROVIDER }}"
            environment: "${{ env.ENVIRONMENT }}"
            region: "${{ env.REGION }}"
            management_cluster: "${{ env.MANAGEMENT_CLUSTER }}"
            team: "${{ env.TEAM }}"
            purpose: "${{ env.PURPOSE }}"
            cost_center: "${{ env.COST_CENTER }}"
            created_at: "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            created_by: "github-actions"
            pr_number: "${{ github.event.pull_request.number }}"
          EOF
          
          # Update the cluster kustomization to include the metadata
          sed -i "/- cluster-deployment.yaml/a \ - k0rdent-metadata.yaml" "$TARGET_DIR/kustomization.yaml"
          
      - name: Commit changes
        run: |
          git add management-clusters/${{ env.MANAGEMENT_CLUSTER }}/k0rdent/cluster-deployments/${{ env.CLUSTER_NAME }}
          git add management-clusters/${{ env.MANAGEMENT_CLUSTER }}/k0rdent/cluster-deployments/kustomization.yaml
          git commit -m "Add ClusterDeployment for ${{ env.CLUSTER_NAME }} on ${{ env.PROVIDER }}"
          git remote set-url origin https://x-access-token:${{ secrets.CLUSTER_REQUEST_PAT }}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
          
      - name: Add merge instructions comment
        run: |
          # Add a comment to the PR with instructions for merging
          gh pr comment ${{ github.event.pull_request.number }} --body "
          ## :white_check_mark: Cluster Configuration Ready
          
          The cluster configuration for **${{ env.CLUSTER_NAME }}** has been prepared and added to this PR.
          
          ### Next Steps:
          1. Review the generated configuration in \`management-clusters/${{ env.MANAGEMENT_CLUSTER }}/k0rdent/cluster-deployments/${{ env.CLUSTER_NAME }}/\`
          2. Make any necessary adjustments to the configuration
          3. **Merge this PR** to trigger the cluster deployment
          
          Once merged, the cluster configuration will be picked up by ArgoCD and k0rdent will create the cluster.
          "
        env:
          GH_TOKEN: ${{ secrets.CLUSTER_REQUEST_PAT }} 